PREFIX  yago: <http://mpii.de/yago/resource/>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT  *
WHERE
  { ?person   yago:discovered  ?discovery .
    ?discovery  yago:influences  ?p .
    ?p        yago:bornOnDate  ?date
  }