BASE    <http://mpii.de/yago/resource/>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT  *
WHERE
  { ?s  <diedIn>              $1 ;
        rdfs:label            ?n ;
        <diedOnDate>          ?d ;
        a                     $2
  }