PREFIX yago: <http://mpii.de/yago/resource/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT *
{
  ?director yago:directed/yago:hasPredecessor/yago:hasPredecessor/rdf:type ?preType;

            yago:produced/yago:isOfGenre/rdfs:label ?label;

            yago:influences ?person.
}