(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(*
t:total number of rows;
a:sum of the first column;
b:sum of the second column;
r:number of rows that consist of only 1's
*)
mdf2[t_, a_, b_, r_] := Binomial[a, r]*Binomial[t - a, b - r]/Binomial[t, b]

mdf2[t_, {a_, b_}, r_] := mdf2[t, a, b, r]

(*
for three columns
*)
mdf3l[t_,a_,b_,c_,r_]:= Sum[mdf2[t, a, b, r1]*mdf2[t, r1, c, r], {r1,Max[a+b-t,0],Min[a,b],1}]

mdf3r[t_, a_, b_, c_, r_] := Sum[mdf2[t, b, c, r1]*mdf2[t, a, r1, r], {r1, Max[c + b - t, 0], Min[b, c], 1}]

(*
for n columns;
c:a list of length n that consist of the sum of each column
*)
bottom[c_, t_] := With[
  {n = Length[c]},
  Max[Plus @@ c - t*(n - 1), 0]]

top[c_] := Min[c]

mdf[t_,c_,r_] :=((*Print["mdf2: ",c,"r: ",r];*)mdf2[t,c,r])/; Length[c] == 2

mdf[t_,c_,r_]:=With[
   {
    c1 = Take[c, Length[c] - 1],tail=Last[c]
    },
(*Print["mdf c: ",c];
Print["bottom",bottom[c1,t],"top",top[c1]];*)
   Sum[mdf[t,c1,r1]*mdf2[t,r1,tail,r], {r1,bottom[c1,t],top[c1],1}]]/; Length[c]>=3

dist2[t_, a_, c_] := ProbabilityDistribution[mdf2[t, a, c, r], {r, Max[a + c - t, 0], Min[a, c], 1}];
