PREFIX yago: <http://mpii.de/yago/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT *
WHERE
{ <http://mpii.de/yago/resource/Joni_Mitchell> yago:produced ?movie .
?movie yago:isOfGenre ?genre .
?genre rdfs:label ?label .
<http://mpii.de/yago/resource/Joni_Mitchell> yago:influences <http://mpii.de/yago/resource/Jon_McLaughlin>
}

