base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <bornIn> <http://mpii.de/yago/resource/Lisbon>. ?s rdfs:label ?n. ?s a <http://mpii.de/yago/resource/wordnet_curate_109983572>. }

