base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <bornIn> <http://mpii.de/yago/resource/St._Louis,_Missouri>. ?s rdfs:label ?n. ?s a <http://mpii.de/yago/resource/wikicategory_United_States_Army_officers>. }

