base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <bornIn> <http://mpii.de/yago/resource/P%C5%99%C3%ADbor>. ?s rdfs:label ?n. ?s a <http://mpii.de/yago/resource/wikicategory_Leaders_ousted_by_a_coup>. }

