base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <bornIn> <http://mpii.de/yago/resource/Buckinghamshire>. ?s rdfs:label ?n. ?s a <http://mpii.de/yago/resource/wikicategory_Olympic_ice_hockey_players_of_Sweden>. }

