base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <bornIn> <http://mpii.de/yago/resource/Celje>. ?s rdfs:label ?n. ?s a <http://mpii.de/yago/resource/wikicategory_Fellows_of_Gonville_and_Caius_College,_Cambridge>. }

