base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <originatesFrom> <http://mpii.de/yago/resource/Carolina_del_Pr%C3%ADncipe,_Antioquia>. ?s rdfs:label ?n. ?s <hasWebsite> <http://www.koolkeith.co.uk> }

