base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <originatesFrom> <http://mpii.de/yago/resource/M%C3%A4nts%C3%A4l%C3%A4>. ?s rdfs:label ?n. ?s <hasWebsite> <http://www.caroleking.com> }

