base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <originatesFrom> <http://mpii.de/yago/resource/Davenport,_Iowa>. ?s rdfs:label ?n. ?s <hasWebsite> <http://www.plastikman.com> }

