base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <diedIn> <http://mpii.de/yago/resource/Lambar%C3%A9n%C3%A9>. ?s rdfs:label ?n. ?s <diedOnDate> ?d. ?s a <http://mpii.de/yago/resource/wikicategory_Saint_Petersburg_State_University_alumni> }

