base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <diedIn> <http://mpii.de/yago/resource/Freiburg_im_Breisgau>. ?s rdfs:label ?n. ?s <diedOnDate> ?d. ?s a <http://mpii.de/yago/resource/wikicategory_Signers_of_the_U.S._Declaration_of_Independence> }

