base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <diedIn> <http://mpii.de/yago/resource/Li%C3%A8ge_(city)>. ?s rdfs:label ?n. ?s <diedOnDate> ?d. ?s a <http://mpii.de/yago/resource/wikicategory_British_colonial_governors_and_administrators> }

