base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select * where { ?s <diedIn> <http://mpii.de/yago/resource/Wilderness,_Western_Cape>. ?s rdfs:label ?n. ?s <diedOnDate> ?d. ?s a <http://mpii.de/yago/resource/wikicategory_Catholic_martyrs_of_the_Early_Modern_era> }

