base <http://mpii.de/yago/resource/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix yago: <http://mpii.de/yago/resource/>

select ?s ?u ?c ?m where { ?s <hasOfficialLanguage> <http://mpii.de/yago/resource/Chamorro_language>. ?s <hasUTCOffset> "0". ?s <hasCapital> ?c. ?s <hasCurrency> ?cur. }

